language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true
  include:
    - name: lsif index src/testRunner
      script:
        - cd src/testRunner && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/tsserver
      script:
        - cd src/tsserver && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/typingsInstallerCore
      script:
        - cd src/typingsInstallerCore && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/tsserverlibrary
      script:
        - cd src/tsserverlibrary && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/tsc
      script:
        - cd src/tsc && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/server
      script:
        - cd src/server && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/instrumenter
      script:
        - cd src/instrumenter && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/harness
      script:
        - cd src/harness && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/watchGuard
      script:
        - cd src/watchGuard && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/cancellationToken
      script:
        - cd src/cancellationToken && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/shims
      script:
        - cd src/shims && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/typescriptServices
      script:
        - cd src/typescriptServices && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/jsTyping
      script:
        - cd src/jsTyping && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/executeCommandLine
      script:
        - cd src/executeCommandLine && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/typingsInstaller
      script:
        - cd src/typingsInstaller && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/compiler
      script:
        - cd src/compiler && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/services
      script:
        - cd src/services && lsif-tsc -p . && ../../src-cli lsif upload
    - name: lsif index src/debug
      script:
        - cd src/debug && lsif-tsc -p . && ../../src-cli lsif upload

branches:
  only:
  - master
  - upload-lsif
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm install
  - npm install -g @sourcegraph/lsif-tsc
  # Download src-cli (cannot download in current directory as `src` as it's already a directory)
  - curl -L https://github.com/sourcegraph/src-cli/releases/download/3.10.13/src_linux_amd64 -o ./src-cli
  - chmod +x ./src-cli

cache:
  directories:
    - node_modules

git:
  depth: 1
