language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true
  include:
    - name: lsif index
      os: linux
      go: 1.14.x
      script:
        - yarn
        - cd src/shims && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/tsc && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/tsserver && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/typingsInstaller && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/watchGuard && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/debug && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/cancellationToken && lsif-tsc -p . && ../../src-cli lsif upload && cd -
        - cd src/testRunner && lsif-tsc -p . && ../../src-cli lsif upload && cd -

branches:
  only:
  - master
  - upload-lsif
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm install
  - npm install -g @sourcegraph/lsif-tsc
  # Download src-cli (cannot download in current directory as `src` as it's already a directory)
  - curl -L https://github.com/sourcegraph/src-cli/releases/download/3.10.13/src_linux_amd64 -o ./src-cli
  - chmod +x ./src-cli

cache:
  directories:
    - node_modules

git:
  depth: 1
