language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true
  include:
    - name: lsif index
    os: linux
    go: 1.14.x
    script:
      - yarn
      - for d in src/shims src/tsc src/tsserver src/typingsInstaller src/watchGuard src/debug src/cancellationToken src/testRunner; do
      -   cd $d
      -   lsif-tsc -p .
      -   src lsif upload
      -   cd -
      - done

branches:
  only:
  - master
  - /^release-.*/

install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
